### PR TITLE
Bincode support with Encode/Decode derived

### PR DESCRIPTION
**Pull request by jguhlin**
Hello. I've added bincode's Encode/Decode derives as an optional feature alongside serde. Feel free to accept or reject, and thanks for this very useful crate!

### CODE REVIEW

**Review by ayazhafiz — APPROVED** [review]
Looks great! Thank you. I'll make in a release in the coming days including this feature.

**Comment by ayazhafiz** [comment]
@jguhlin looks like this needs a `cargo fmt`.

**Comment by jguhlin** [comment]
Fmt run, but let me know if you'd like anything else! Cheers

**Review by ayazhafiz — APPROVED** [review]

**Comment by ayazhafiz** [comment]
Thanks for the contribution @jguhlin, I'll make a release for this soon.

**Comment by ayazhafiz** [comment]
@jguhlin , this is available in https://github.com/ayazhafiz/xorf/releases/tag/0.9.0. Thank you so much!

**Pull request merged**
