### PR TITLE
Fix build panic due to subtraction overflow when the count of keys is 1

### LINKED ISSUE #47: panic when the number of keys is 1
The following code panics with message `attempt to subtract with overflow`

```
BinaryFuse8::try_from(&vec![1u64])
```

### PR DESCRIPTION
**Pull request by youjiali1995**
close #47

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### CODE REVIEW

**Comment by ayazhafiz** [comment]
Hey, sorry for the delay! This looks great! Thanks for your contribution. I think the test failure is a flake.

**Comment by jakelee8** [comment]
@ayazhafiz could you release `0.8.1` for this bug fix? Thank you!

**Comment by ayazhafiz** [comment]
@jakelee8 sorry for the delay here - just published! Thanks for pinging me.

**Comment by jakelee8** [comment]
Thank you!

**Pull request merged**
